/// <reference types="vitest" />

import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'
import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join, resolve, extname } from 'node:path'

// Custom KEL Protocol Plugin: Fuses static assets into a Core Engine TS dictionary
function emitBase64Assets() {
  return {
    name: 'emit-base64-assets',
    closeBundle() {
      const distPath = resolve(import.meta.dirname, 'dist')
      const outFilePath = resolve(
        import.meta.dirname,
        '../src/cli/webAssets.ts'
      )

      const mimeTypes: Record<string, string> = {
        '.html': 'text/html',
        '.js': 'application/javascript',
        '.css': 'text/css',
        '.svg': 'image/svg+xml',
        '.json': 'application/json',
        '.ico': 'image/x-icon',
        '.woff2': 'font/woff2',
      }

      const assets: Record<string, { contentType: string; content: string }> =
        {}

      const walkSync = (dir: string) => {
        const files = readdirSync(dir)
        for (const file of files) {
          const filepath = join(dir, file)
          if (statSync(filepath).isDirectory()) {
            walkSync(filepath)
          } else {
            const ext = extname(filepath).toLowerCase()
            // Convert physical path to a web route (e.g., /assets/index-xyz.js)
            const route = filepath.replace(distPath, '').replace(/\\/g, '/')
            const content = readFileSync(filepath, 'base64')
            const contentType = mimeTypes[ext] || 'application/octet-stream'

            assets[route] = { contentType, content }
          }
        }
      }

      walkSync(distPath)

      // Generate the TypeScript file for the CLI
      const tsContent = `// AUTO-GENERATED BY VITE - DO NOT EDIT\nexport const webAssets: Record<string, { contentType: string; content: string }> = ${JSON.stringify(assets, null, 2)};\n`

      writeFileSync(outFilePath, tsContent, 'utf-8')
      console.log(
        `\n✓ [KEL Protocol] Injected ${Object.keys(assets).length} UI assets into the Core Engine perimeter.`
      )
    },
  }
}

export default defineConfig({
  plugins: [react(), tailwindcss(), emitBase64Assets()],
  build: {
    emptyOutDir: true,
    chunkSizeWarningLimit: 2000,
  },
  test: {
    environment: 'jsdom',
    globals: true,
    setupFiles: './src/setupTests.ts',
  },
})
