comment:
  layout: "diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false

coverage:
  status:
    project:
      default:
        # 'auto' sets the target to the current coverage of your main branch
        target: auto 
        # Allows a 1% drop without any warning
        threshold: 1% 
        # This prevents Codecov from failing your GitHub CI check
        informational: true 
    patch:
      default:
        # Only tracks coverage on the specific lines you changed in the PR
        target: auto
        threshold: 0%
        informational: true
