/**
 * Build script for embedding Web UI assets into the CLI
 */
import {
  readFileSync,
  writeFileSync,
  readdirSync,
  statSync,
  existsSync,
} from 'node:fs'
import { join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'
import { dirname } from 'node:path'

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const rootDir = dirname(__dirname)

const distDir = join(rootDir, 'dist')
const outputFile = join(rootDir, 'src', 'cli', 'web-assets.ts')

if (!existsSync(distDir)) {
  console.error(
    `❌ Error: dist/ directory not found. Please run 'npm run build' first.`
  )
  process.exit(1)
}

const getMimeType = (ext: string) => {
  const mimes: Record<string, string> = {
    '.html': 'text/html',
    '.css': 'text/css',
    '.js': 'application/javascript',
    '.json': 'application/json',
    '.png': 'image/png',
    '.jpg': 'image/jpeg',
    '.jpeg': 'image/jpeg',
    '.svg': 'image/svg+xml',
    '.ico': 'image/x-icon',
    '.woff': 'font/woff',
    '.woff2': 'font/woff2',
    '.ttf': 'font/ttf',
  }
  return mimes[ext] || 'application/octet-stream'
}

function walk(dir: string, fileList: string[] = []) {
  const files = readdirSync(dir).sort()
  for (const file of files) {
    const filePath = join(dir, file)
    if (statSync(filePath).isDirectory()) {
      walk(filePath, fileList)
    } else {
      fileList.push(filePath)
    }
  }
  return fileList
}

const files = walk(distDir)
const assets: Record<string, { contentType: string; content: string }> = {}

for (const filePath of files) {
  const relPath = '/' + relative(distDir, filePath).replace(/\\/g, '/')
  const ext = filePath.substring(filePath.lastIndexOf('.')).toLowerCase()
  const content = readFileSync(filePath).toString('base64')

  // Exclude SEA artifacts which might be in dist/sea
  if (relPath.startsWith('/sea/')) continue

  // Skip non-deterministic or unnecessary artifacts
  if (
    filePath.endsWith('.map') ||
    filePath.endsWith('concatenator-bundle-stats.html')
  )
    continue

  assets[relPath] = {
    contentType: getMimeType(ext),
    content,
  }
}

const sortedAssets = Object.keys(assets)
  .sort()
  .reduce(
    (acc, key) => {
      acc[key] = assets[key]
      return acc
    },
    {} as typeof assets
  )

const tsContent = `// Auto-generated by scripts/build-web-assets.ts
// Do not edit manually

export const webAssets = ${JSON.stringify(sortedAssets, null, 2)};
`

writeFileSync(outputFile, tsContent, 'utf-8')
console.log(
  `✅ Successfully embedded ${Object.keys(assets).length} web assets into src/cli/web-assets.ts`
)
